export const interstellarApi = [
  {
    id: "lune",
    englishName: "Moon",
    moons: null,
    gravity: 1.62,
    aroundPlanet: {
      planet: "terre",
    },
    bodyType: "Moon",
  },
  {
    id: "phobos",
    englishName: "Phobos",
    moons: null,
    gravity: 0.0057,
    aroundPlanet: {
      planet: "mars",
    },
    bodyType: "Moon",
  },
  {
    id: "deimos",
    englishName: "Deimos",
    moons: null,
    gravity: 0.003,
    aroundPlanet: {
      planet: "mars",
    },
    bodyType: "Moon",
  },
  {
    id: "io",
    englishName: "Io",
    moons: null,
    gravity: 1.79,
    aroundPlanet: {
      planet: "jupiter",
    },
    bodyType: "Moon",
  },
  {
    id: "europe",
    englishName: "Europa",
    moons: null,
    gravity: 1.31,
    aroundPlanet: {
      planet: "jupiter",
    },
    bodyType: "Moon",
  },
  {
    id: "ganymede",
    englishName: "Ganymede",
    moons: null,
    gravity: 1.428,
    aroundPlanet: {
      planet: "jupiter",
    },
    bodyType: "Moon",
  },
  {
    id: "callisto",
    englishName: "Callisto",
    moons: null,
    gravity: 1.235,
    aroundPlanet: {
      planet: "jupiter",
    },
    bodyType: "Moon",
  },
  {
    id: "amalthee",
    englishName: "Amalthea",
    moons: null,
    gravity: 0.02,
    aroundPlanet: {
      planet: "jupiter",
    },
    bodyType: "Moon",
  },
  {
    id: "himalia",
    englishName: "Himalia",
    moons: null,
    gravity: 0.062,
    aroundPlanet: {
      planet: "jupiter",
    },
    bodyType: "Moon",
  },
  {
    id: "mimas",
    englishName: "Mimas",
    moons: null,
    gravity: 0.0,
    aroundPlanet: {
      planet: "saturne",
    },
    bodyType: "Moon",
  },
  {
    id: "encelade",
    englishName: "Enceladus",
    moons: null,
    gravity: 0.0,
    aroundPlanet: {
      planet: "saturne",
    },
    bodyType: "Moon",
  },
  {
    id: "tethys",
    englishName: "Tethys",
    moons: null,
    gravity: 0.0,
    aroundPlanet: {
      planet: "saturne",
    },
    bodyType: "Moon",
  },
  {
    id: "dione",
    englishName: "Dione",
    moons: null,
    gravity: 0.0,
    aroundPlanet: {
      planet: "saturne",
    },
    bodyType: "Moon",
  },
  {
    id: "rhea",
    englishName: "Rhea",
    moons: null,
    gravity: 0.0,
    aroundPlanet: {
      planet: "saturne",
    },
    bodyType: "Moon",
  },
  {
    id: "titan",
    englishName: "Titan",
    moons: null,
    gravity: 0.0,
    aroundPlanet: {
      planet: "saturne",
    },
    bodyType: "Moon",
  },
  {
    id: "triton",
    englishName: "Triton",
    moons: null,
    gravity: 0.78,
    aroundPlanet: {
      planet: "neptune",
    },
    bodyType: "Moon",
  },
  {
    id: "nereide",
    englishName: "Nereid",
    moons: null,
    gravity: 0.071,
    aroundPlanet: {
      planet: "neptune",
    },
    bodyType: "Moon",
  },
  {
    id: "uranus",
    englishName: "Uranus",
    moons: null,
    gravity: 8.87,
    aroundPlanet: null,
    bodyType: "Planet",
  },
  {
    id: "pluton",
    englishName: "Pluto",
    moons: null,
    gravity: 0.62,
    aroundPlanet: null,
    bodyType: "Dwarf Planet",
  },
  {
    id: "neptune",
    englishName: "Neptune",
    moons: ["Triton", "Néreïde"],
    gravity: 11.15,
    aroundPlanet: null,
    bodyType: "Planet",
  },
  {
    id: "jupiter",
    englishName: "Jupiter",
    moons: ["Io", "Europe", "Ganymède", "Callisto", "Amalthée", "Himalia"],
    gravity: 24.79,
    aroundPlanet: null,
    bodyType: "Planet",
  },
  {
    id: "mars",
    englishName: "Mars",
    moons: ["Phobos", "Deïmos"],
    gravity: 3.71,
    aroundPlanet: null,
    bodyType: "Planet",
  },
  {
    id: "mercure",
    englishName: "Mercury",
    moons: null,
    gravity: 3.7,
    aroundPlanet: null,
    bodyType: "Planet",
  },
  {
    id: "saturne",
    englishName: "Saturn",
    moons: ["Mimas", "Encelade", "Téthys", "Dioné", "Rhéa", "Titan"],
    gravity: 10.44,
    aroundPlanet: null,
    bodyType: "Planet",
  },
  {
    id: "venus",
    englishName: "Venus",
    moons: null,
    gravity: 8.87,
    aroundPlanet: null,
    bodyType: "Planet",
  },
];
